apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.registry.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "webservice.labels" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "service.registry.secret" . }}
---