{{ if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "istio.service.gateway.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "webservice.labels" . | indent 4 }}
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  {{- toYaml .Values.istio.gateway.servers | nindent 4 }}
{{ end }}