{{ if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "istio.service.virtualService.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "webservice.labels" . | indent 4 }}
spec:
  hosts:
  {{- toYaml .Values.istio.virtualService.hosts | nindent 4 }}
  gateways:
  - {{ include "istio.service.gateway.name" . }}
  http:
  - match:
    - uri:
        prefix: {{ .Values.istio.virtualService.uriPrefix }}/
    - uri:
        prefix: {{ .Values.istio.virtualService.uriPrefix }}
#    rewrite:
#      uri: /
    route:
    - destination:
        host: my-app-webservice.dev.svc.cluster.local
        port:
          number: {{ .Values.service.httpPort }}
    timeout: {{ .Values.istio.virtualService.maxTimeout }}
{{ end }}